### ISSUE TITLE
Disables Damage in Preview Mode

### ISSUE THREAD

**Issue by DeltaNovahlis** [dankmeme01/globed2#135]
When I enable Globed for some reason, Damage in preview mode is absolutely gone

**Comment by Flyingturtle215** [comment]
I am experiencing this too, here's some more information:


The game acts as if "Ignore Damage" is enabled when playtesting in the editor with Globed enabled, even when it is not.

Expected behavior: hazards (spikes, saws) should kill the player when playtesting in the editor

Actual behavior: hazards do not kill the player when playtesting, even with Ignore Damage disabled. However, colliding with blocks does kill the player, similar to vanilla GD's Ignore Damage mode.

**Comment by dankmeme01** [comment]
fixed in v1.3.4
