### ISSUE TITLE
[SUGGEST] Globed sends too much requests

### ISSUE THREAD

**Issue by MegaSa1nt** [dankmeme01/globed2#165]
Hi! My Globed Central server sends too much requests

![Screenshot_20240502-073210.png](https://github.com/dankmeme01/globed2/assets/49565695/977faaea-6bca-41fc-92fa-560c92e359fd)

Funny part, that it sends so much requests it literally forced me to move my GDPS to different hosting lol

![image-26.png](https://github.com/dankmeme01/globed2/assets/49565695/47857ae6-8534-45d5-9044-6582bd3441af)

```
Hello!
Reg.ru Domain Name Registrar welcomes you!

You are the owner of the hosting service ||xXXXXXXX|| (Reg.Host-0 ||xXXXXXXX||).
We inform you that the CPU usage limit of 4% for the Host-0 tariff plan has been exceeded on the ||xXXXXXXX|| account.

If the CPU load remains high, your account will be blocked.
```
I want to suggest to change time between sending message check requests

**Comment by dankmeme01** [comment]
The account verification system sends a request every 2 seconds - this is a short interval but it's intentional, to make authentication as fast and smooth as possible.

However if there's a need for it, I could make the refresh interval an option that you can change in the configuration. Though keep in mind that if you set a higher interval, there's a chance you will start getting HTTP timeout errors more often on the client.

**Comment by MegaSa1nt** [comment]
Well, i forgot to mention, that i host 2 GDPSs on my hosting, therefore i host 2 Globed servers lol
I think it will be helpful for bad hostings (free hosts and etc)

**Comment by dankmeme01** [comment]
added a `refresh_interval` option in https://github.com/dankmeme01/globed2/commit/f7a2199725da7df100ebe972eef6e4acf1af2893, will be available in the next update of the server (which will happen when the mod updates)

**Comment by MegaSa1nt** [comment]
Thank you very much ❤️
